# arduino-test-compile-ActionTest.yml
# Github workflow script for testing the arduino-test-compile action development.
#
# Copyright (C) 2020  Armin Joachimsmeyer
# https://github.com/ArminJo/Github-Actions
# License: MIT
#

# This is the name of the workflow, visible on GitHub UI.
name: arduino-test-compile-ActionTest
on:
  workflow_dispatch: # To run it manually
    description: 'manual build check'
  push: # see: https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
    paths:
    - '**.ino'
    - '**.cpp'
    - '**.h'
    - 'arduino-test-compile.sh'
    - 'action.yml'
    - '**arduino-test-compile-ActionTest.yml'

jobs:
  build:
    name: ${{ matrix.arduino-boards-fqbn }} - test compiling examples

    runs-on: ubuntu-latest # ubuntu-latest # I picked Ubuntu to use shell scripts.

    env:
      # Comma separated list without double quotes around the list.
      REQUIRED_LIBRARIES: Adafruit NeoPixel@1.3.4,Servo@1.1.5
#      CLI_VERSION: latest

    strategy:
      matrix:
        # The matrix will produce one job for each configuration parameter of type `arduino-boards-fqbn`
        # In the Arduino IDE, the fqbn is printed in the first line of the verbose output for compilation as parameter -fqbn=... for the "arduino-builder -dump-prefs" command
        #
        # Examples: arduino:avr:uno, arduino:avr:leonardo, arduino:avr:nano, arduino:avr:mega
        # arduino:sam:arduino_due_x, arduino:samd:arduino_zero_native"
        # ATTinyCore:avr:attinyx5:chip=85,clock=1internal, digistump:avr:digispark-tiny, digistump:avr:digispark-pro
        # STMicroelectronics:stm32:GenF1:pnum=BLUEPILL_F103C8
        # esp8266:esp8266:huzzah:eesz=4M3M,xtal=80, esp32:esp32:featheresp32:FlashFreq=80
        # You may add a suffix behind the fqbn with "|" to specify one board for e.g. different compile options like arduino:avr:uno|trace
        #############################################################################################################
        arduino-boards-fqbn:
          - arduino:avr:uno
          - arduino:avr:uno|trace
          - arduino:avr:uno|All-DEBUG
          - ATTinyCore:avr:attinyx5:chip=85,clock=1internal # to check using 2 cores
          - esp8266:esp8266:huzzah:eesz=4M3M,xtal=80
          - esp32:esp32:featheresp32:FlashFreq=80

        # Specify parameters for each board.
        #############################################################################################################
        include:
          - arduino-boards-fqbn: arduino:avr:uno|All-DEBUG # Uno board with -DDEBUG for all examples
            build-properties:
              All: -DDEBUG

          - arduino-boards-fqbn: arduino:avr:uno|trace # Uno board with different build properties
            arduino-platform: arduino:avr@1.8.1
            build-properties:
              All: -DDEBUG -DTRACE

          - arduino-boards-fqbn: ATTinyCore:avr:attinyx5:chip=85,clock=1internal
            arduino-platform: digistump:avr,ATTinyCore:avr
            platform-url: http://drazzy.com/package_drazzy.com_index.json,https://raw.githubusercontent.com/ArminJo/DigistumpArduino/master/package_digistump_index.json
            build-properties:
              WhistleSwitch: -DFREQUENCY_RANGE_LOW # Dummy entry

          - arduino-boards-fqbn: esp8266:esp8266:huzzah:eesz=4M3M,xtal=80
            #"<URL> <URL>" whis space as separator is deprecated but works also
            #platform-url: "https://arduino.esp8266.com/stable/package_esp8266com_index.json https://raw.githubusercontent.com/ArminJo/DigistumpArduino/master/package_digistump_index.json"
            platform-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json

          - arduino-boards-fqbn: esp32:esp32:featheresp32:FlashFreq=80
            platform-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
            sketches-exclude: dummy

      # Do not cancel all jobs / architectures if one job fails
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Checkout custom library
        uses: actions/checkout@master
        with:
          repository: ArminJo/ATtinySerialOut
          ref: master
          path: CustomLibrary # must match the pattern *Custom*

      # Test of the arduino-test-compile action
      - name: Compile all examples using the arduino-test-compile action
        uses: ArminJo/arduino-test-compile@master
        with:
          arduino-board-fqbn: ${{ matrix.arduino-boards-fqbn }}
          arduino-platform: ${{ matrix.arduino-platform }}
          platform-url: ${{ matrix.platform-url }}
          required-libraries: ${{ env.REQUIRED_LIBRARIES }}
          sketches-exclude: ${{ matrix.sketches-exclude }}
          build-properties: ${{ toJson(matrix.build-properties) }}
          sketch-names: test.ino
          sketch-names-find-start: test
          debug-compile: true
          debug-install: true
